CREATE SCHEMA maintenance AUTHORIZATION dbo
GO

CREATE TABLE maintenance.Areas
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Name] VARCHAR(255) NOT NULL
)
GO

INSERT INTO maintenance.Areas VALUES ('8A812F08-0647-443B-8FA3-A98C3B9493A7', 'Area 1');
INSERT INTO maintenance.Areas VALUES ('42441057-b6c1-4852-9ea7-1f382f99e4eb', 'Area 2');
GO

CREATE SCHEMA app AUTHORIZATION dbo
GO

CREATE TABLE app.OutboxMessages
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[OccurredOn] DATETIME2 NOT NULL,
	[Type] VARCHAR(255) NOT NULL,
	[Data] VARCHAR(MAX) NOT NULL,
	[ProcessedDate] DATETIME2 NULL,
	CONSTRAINT [PK_app_OutboxMessages_Id] PRIMARY KEY ([Id] ASC)
)
GO

CREATE TABLE app.InternalCommands
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[EnqueueDate] DATETIME2 NOT NULL,
	[Type] VARCHAR(255) NOT NULL,
	[Data] VARCHAR(MAX) NOT NULL,
	[ProcessedDate] DATETIME2 NULL,
	CONSTRAINT [PK_app_InternalCommands_Id] PRIMARY KEY ([Id] ASC)
)
GO
